        // ── Helper: Excel number format (standard SheetJS supports 'z' property) ──
        function xn(val, fmt) {
            const cell = { v: val, t: typeof val === 'number' ? 'n' : 's' };
            if (fmt) cell.z = fmt;
            return cell;
        }

        // ── COMPREHENSIVE PROFESSIONAL EXCEL EXPORT ──
        // Standard SheetJS (community) supports: data, !cols, !merges, cell.z (number format)
        // It does NOT write colors/borders/bold. We use clean structure + number formats.
        async function exportProfessionalExcel() {
            if (!modelData) { showToast('Run analysis first'); return; }
            setExportProgress(5, 'Preparing Excel workbook...', 'Building 8 professional sheets');

            const wb = XLSX.utils.book_new();
            const p = getCurrentParams();
            const years = ['Y1', 'Y2', 'Y3', 'Y4', 'Y5'];
            const now = new Date();
            const dateStr = now.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
            const safeName = (modelData.company || 'Company').replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '_');

            // ── Sheet 1: Cover ──
            setExportProgress(10, 'Creating cover sheet...', '');
            const coverData = [
                ['', '', '', '', '', ''],
                ['EQUITY RESEARCH REPORT', '', '', '', '', ''],
                ['', '', '', '', '', ''],
                [modelData.company.toUpperCase(), '', '', '', '', ''],
                ['', '', '', '', '', ''],
                ['DCF Valuation Model | 5-Year Projection', '', '', '', '', ''],
                ['Report Date: ' + dateStr, '', '', '', '', ''],
                ['', '', '', '', '', ''],
                ['', '', '', '', '', ''],
                ['━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', '', '', '', '', ''],
                ['', '', '', '', '', ''],
                ['INVESTMENT RATING', '', '', '', '', ''],
                ['', '', '', '', '', ''],
                [modelData.rating, '', '', '', '', ''],
                ['', '', '', '', '', ''],
                [(modelData.upside > 0 ? '+' : '') + modelData.upside.toFixed(1) + '% Upside', '', '', '', '', ''],
                ['', '', '', '', '', ''],
                ['', '', '', '', '', ''],
                ['KEY METRICS', '', '', '', '', ''],
                ['', '', '', '', '', ''],
                ['Current Price', 'Fair Value', 'Target Price', 'EV (Cr)', 'Eq Value (Cr)', ''],
                [xn(modelData.price, '₹#,##0.00'), xn(modelData.dcfPrice, '₹#,##0.00'), xn(modelData.target, '₹#,##0.00'), xn(modelData.ev, '#,##0'), xn(modelData.eq, '#,##0'), ''],
                ['', '', '', '', '', ''],
                ['', '', '', '', '', ''],
                ['DISCLAIMER', '', '', '', '', ''],
                ['This report is for informational purposes only and does not constitute investment advice.', '', '', '', '', ''],
                ['Generated by dsFinancial Modelling Engine.', '', '', '', '', ''],
            ];
            let wsCover = XLSX.utils.aoa_to_sheet(coverData);
            wsCover['!cols'] = [{ wch: 22 }, { wch: 18 }, { wch: 18 }, { wch: 18 }, { wch: 18 }, { wch: 18 }];
            wsCover['!merges'] = [
                { s: { r: 1, c: 0 }, e: { r: 1, c: 5 } },
                { s: { r: 3, c: 0 }, e: { r: 3, c: 5 } },
                { s: { r: 5, c: 0 }, e: { r: 5, c: 5 } },
                { s: { r: 6, c: 0 }, e: { r: 6, c: 5 } },
                { s: { r: 9, c: 0 }, e: { r: 9, c: 5 } },
                { s: { r: 11, c: 0 }, e: { r: 11, c: 5 } },
                { s: { r: 13, c: 0 }, e: { r: 13, c: 5 } },
                { s: { r: 15, c: 0 }, e: { r: 15, c: 5 } },
                { s: { r: 18, c: 0 }, e: { r: 18, c: 5 } },
                { s: { r: 23, c: 0 }, e: { r: 23, c: 5 } },
                { s: { r: 24, c: 0 }, e: { r: 24, c: 5 } },
                { s: { r: 25, c: 0 }, e: { r: 25, c: 5 } },
            ];
            XLSX.utils.book_append_sheet(wb, wsCover, 'Cover');

            // ── Sheet 2: Income Statement ──
            setExportProgress(22, 'Building Income Statement...', '');
            const revCAGR = ((Math.pow(modelData.rev[4] / modelData.rev[0], 0.2) - 1) * 100);
            const ebitdaCAGR = ((Math.pow(modelData.ebitda[4] / modelData.ebitda[0], 0.2) - 1) * 100);
            const niCAGR = ((Math.pow(modelData.ni[4] / modelData.ni[0], 0.2) - 1) * 100);
            const isData = [
                [modelData.company + ' -- Income Statement (Rs Cr)', '', '', '', '', '', ''],
                [''],
                ['Line Item', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'CAGR'],
            ];
            const isRows = [
                ['Revenue', ...modelData.rev, revCAGR],
                ['YoY Growth %', '', ...modelData.rev.slice(1).map((r, i) => (r / modelData.rev[i] - 1) * 100), ''],
                [''],
                ['EBITDA', ...modelData.ebitda, ebitdaCAGR],
                ['EBITDA Margin %', ...modelData.ebitda.map((e, i) => e / modelData.rev[i] * 100), ''],
                [''],
                ['Depreciation & Amortization', ...modelData.rev.map(r => r * 0.03), ''],
                ['EBIT', ...modelData.ebit, ''],
                ['EBIT Margin %', ...modelData.ebit.map((e, i) => e / modelData.rev[i] * 100), ''],
                [''],
                ['Interest Expense', ...modelData.rev.map(() => p.netDebt * 0.08), ''],
                ['EBT', ...modelData.ebit.map((e, i) => e - p.netDebt * 0.08), ''],
                ['Taxes', ...modelData.ebit.map((e, i) => Math.max(0, (e - p.netDebt * 0.08) * (p.taxRate / 100))), ''],
                ['Effective Tax Rate %', ...modelData.ebit.map(() => p.taxRate), ''],
                [''],
                ['Net Income', ...modelData.ni, niCAGR],
                ['Net Margin %', ...modelData.ni.map((n, i) => n / modelData.rev[i] * 100), ''],
                [''],
                ['Shares Outstanding (Cr)', ...Array(5).fill(p.shares), ''],
                ['EPS (Rs)', ...modelData.ni.map(n => n / p.shares), ''],
            ];
            isRows.forEach(row => {
                const isPct = row[0].includes('%') || row[0].includes('Margin') || row[0].includes('Growth') || row[0].includes('Rate');
                const isBold = ['Revenue', 'EBITDA', 'EBIT', 'EBT', 'Net Income', ''].includes(row[0]);
                isData.push(row.map((v, i) => {
                    if (v === '') return '';
                    if (typeof v === 'number') {
                        if (isPct) return xn(v / 100, '0.0%');
                        if (row[0] === 'EPS (Rs)') return xn(v, '0.00');
                        return xn(v, '#,##0.0');
                    }
                    return v;
                }));
            });
            let wsIS = XLSX.utils.aoa_to_sheet(isData);
            wsIS['!cols'] = [{ wch: 32 }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 12 }];
            wsIS['!merges'] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 6 } }];
            XLSX.utils.book_append_sheet(wb, wsIS, 'Income Statement');

            // ── Sheet 3: Cash Flow Statement ──
            setExportProgress(35, 'Building Cash Flow Statement...', '');
            const daArr = modelData.rev.map(r => r * 0.03);
            const capexArr = modelData.rev.map(r => r * 0.05);
            const cfData = [
                [modelData.company + ' -- Cash Flow Statement (Rs Cr)', '', '', '', '', ''],
                [''],
                ['Line Item', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5'],
                ['CASH FLOW FROM OPERATIONS', '', '', '', '', ''],
                ['Net Income', ...modelData.ni],
                ['(+/-) Depreciation & Amortization', ...daArr],
                ['(+/-) Changes in Working Capital', ...modelData.rev.map(r => -r * 0.02)],
                ['Cash Flow from Operations', ...modelData.ni.map((n, i) => n + daArr[i] - modelData.rev[i] * 0.02)],
                [''],
                ['CASH FLOW FROM INVESTING', '', '', '', '', ''],
                ['Capital Expenditures', ...capexArr],
                ['Acquisitions / Divestitures', ...[0, 0, 0, 0, 0]],
                ['Cash Flow from Investing', ...capexArr.map(c => -c)],
                [''],
                ['CASH FLOW FROM FINANCING', '', '', '', '', ''],
                ['Debt Issued / (Repaid)', ...[0, 0, 0, 0, 0]],
                ['Dividends Paid', ...modelData.ni.map(n => -n * 0.3)],
                ['Equity Issued', ...[0, 0, 0, 0, 0]],
                ['Cash Flow from Financing', ...modelData.ni.map(n => -n * 0.3)],
                [''],
                ['NET CHANGE IN CASH', ...modelData.ni.map((n, i) => n + daArr[i] - modelData.rev[i] * 0.02 - capexArr[i] - n * 0.3)],
                ['Beginning Cash Balance', ...Array(5).fill(50)],
                ['Ending Cash Balance', ...modelData.ni.map((n, i) => 50 + n + daArr[i] - modelData.rev[i] * 0.02 - capexArr[i] - n * 0.3)],
            ];
            let wsCF = XLSX.utils.aoa_to_sheet(cfData);
            wsCF['!cols'] = [{ wch: 36 }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 14 }];
            wsCF['!merges'] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 5 } }];
            XLSX.utils.book_append_sheet(wb, wsCF, 'Cash Flow');

            // ── Sheet 4: DCF Model ──
            setExportProgress(48, 'Building DCF Model...', '');
            const dcfWsData = [
                [modelData.company + ' -- Discounted Cash Flow Model (Rs Cr)', '', '', '', '', '', '', '', '', '', '', '', ''],
                [''],
                ['Assumptions'],
                ['WACC', p.wacc + '%', '', 'Terminal Growth Rate', p.tgr + '%', ''],
                ['Net Debt', p.netDebt, '', 'Shares Outstanding (Cr)', p.shares, ''],
                ['Tax Rate', p.taxRate + '%', '', '', '', ''],
                [''],
                ['Projected Free Cash Flows'],
                [''],
                ['Year', 'Revenue', 'EBITDA', 'D&A', 'EBIT', 'Tax', 'NOPAT', 'D&A', 'CapEx', 'dWC', 'FCF', 'DF', 'PV of FCF'],
            ];
            modelData.rev.forEach((rev, i) => {
                const ebitda = modelData.ebitda[i];
                const da = rev * 0.03;
                const ebit = modelData.ebit[i];
                const tax = Math.max(0, (ebit - p.netDebt * 0.08) * (p.taxRate / 100));
                const nopat = ebit - tax;
                const capex = rev * 0.05;
                const dwc = -rev * 0.02;
                const fcf = modelData.fcf[i];
                const df = 1 / Math.pow(1 + p.wacc / 100, i + 1);
                const pv = fcf * df;
                dcfWsData.push([years[i], rev, ebitda, da, ebit, tax, nopat, da, capex, dwc, fcf, df, pv]);
            });
            dcfWsData.push(
                [''],
                ['DCF Valuation Summary'],
                [''],
                ['Sum of PV of FCF (Y1-Y5)', '', '', '', '', '', '', '', '', '', '', '', xn(modelData.pvFcf, '#,##0.0')],
                ['Terminal Value', '', '', '', '', '', '', '', '', '', '', '', xn(modelData.tv, '#,##0.0')],
                ['PV of Terminal Value', '', '', '', '', '', '', '', '', '', '', '', xn(modelData.pvTv, '#,##0.0')],
                ['Enterprise Value', '', '', '', '', '', '', '', '', '', '', '', xn(modelData.ev, '#,##0.0')],
                [''],
                ['(-) Net Debt', '', '', '', '', '', '', '', '', '', '', '', xn(-p.netDebt, '#,##0.0')],
                ['Equity Value', '', '', '', '', '', '', '', '', '', '', '', xn(modelData.eq, '#,##0.0')],
                ['Shares Outstanding (Cr)', '', '', '', '', '', '', '', '', '', '', '', xn(p.shares, '#,##0.0')],
                ['Fair Value per Share (Rs)', '', '', '', '', '', '', '', '', '', '', '', xn(modelData.dcfPrice, 'Rs#,##0.00')],
                [''],
                ['Current Market Price (Rs)', '', '', '', '', '', '', '', '', '', '', '', xn(modelData.price, 'Rs#,##0.00')],
                ['Upside / (Downside)', '', '', '', '', '', '', '', '', '', '', '', xn(modelData.upside / 100, '+0.0%;-0.0%;0.0%')]
            );
            let wsDCF = XLSX.utils.aoa_to_sheet(dcfWsData);
            wsDCF['!cols'] = [{ wch: 28 }, { wch: 13 }, { wch: 13 }, { wch: 11 }, { wch: 13 }, { wch: 11 }, { wch: 13 }, { wch: 11 }, { wch: 11 }, { wch: 11 }, { wch: 13 }, { wch: 11 }, { wch: 14 }];
            wsDCF['!merges'] = [
                { s: { r: 0, c: 0 }, e: { r: 0, c: 12 } },
                { s: { r: 18, c: 0 }, e: { r: 18, c: 11 } },
                { s: { r: 19, c: 0 }, e: { r: 19, c: 11 } },
                { s: { r: 20, c: 0 }, e: { r: 20, c: 11 } },
                { s: { r: 21, c: 0 }, e: { r: 21, c: 11 } },
                { s: { r: 22, c: 0 }, e: { r: 22, c: 11 } },
                { s: { r: 24, c: 0 }, e: { r: 24, c: 11 } },
                { s: { r: 25, c: 0 }, e: { r: 25, c: 11 } },
                { s: { r: 26, c: 0 }, e: { r: 26, c: 11 } },
                { s: { r: 27, c: 0 }, e: { r: 27, c: 11 } },
                { s: { r: 29, c: 0 }, e: { r: 29, c: 11 } },
                { s: { r: 30, c: 0 }, e: { r: 30, c: 11 } },
            ];
            XLSX.utils.book_append_sheet(wb, wsDCF, 'DCF Model');

            // ── Sheet 5: Valuation Summary ──
            setExportProgress(58, 'Building Valuation Summary...', '');
            const peVal = modelData.eq / modelData.ni[4] * 20;
            const evEbitdaVal = modelData.ev / modelData.ebitda[4] * 8;
            const grahamVal = Math.sqrt(22.5 * (modelData.ni[4] / p.shares) * 50);
            const blendedVal = modelData.dcfPrice * 0.40 + peVal * 0.25 + evEbitdaVal * 0.20 + grahamVal * 0.15;
            const valSumData = [
                ['Valuation Summary -- ' + modelData.company, '', '', '', '', ''],
                [''],
                ['Method', 'Fair Value (Rs)', 'Upside', 'Signal', 'Weight', 'Weighted Value'],
                ['DCF (Primary)', xn(modelData.dcfPrice, 'Rs#,##0'), xn(modelData.upside / 100, '0.0%'), modelData.rating, '40%', xn(modelData.dcfPrice * 0.40, 'Rs#,##0')],
                ['P/E Multiple (20x)', xn(peVal, 'Rs#,##0'), xn((peVal / modelData.price - 1), '0.0%'), peVal > modelData.price * 1.2 ? 'BUY' : peVal > modelData.price ? 'HOLD' : 'SELL', '25%', xn(peVal * 0.25, 'Rs#,##0')],
                ['EV/EBITDA (8x)', xn(evEbitdaVal, 'Rs#,##0'), xn((evEbitdaVal / modelData.price - 1), '0.0%'), 'BUY', '20%', xn(evEbitdaVal * 0.20, 'Rs#,##0')],
                ['Graham Formula', xn(grahamVal, 'Rs#,##0'), xn((grahamVal / modelData.price - 1), '0.0%'), 'HOLD', '15%', xn(grahamVal * 0.15, 'Rs#,##0')],
                [''],
                ['Blended Fair Value (Weighted Average)', '', '', '', '', xn(blendedVal, 'Rs#,##0')],
                [''],
                ['Key Valuation Metrics'],
                [''],
                ['Enterprise Value', xn(modelData.ev, '#,##0'), '', 'Equity Value', xn(modelData.eq, '#,##0'), ''],
                ['Implied EV/EBITDA', xn(modelData.ev / modelData.ebitda[4], '0.0x'), '', 'Implied P/E', xn(modelData.eq / modelData.ni[4], '0.0x'), ''],
                ['Implied P/B', xn(modelData.eq / (modelData.equity[4] || 100), '0.0x'), '', 'FCF Yield', xn(modelData.fcf[4] / modelData.eq, '0.0%'), ''],
            ];
            let wsVal = XLSX.utils.aoa_to_sheet(valSumData);
            wsVal['!cols'] = [{ wch: 28 }, { wch: 18 }, { wch: 14 }, { wch: 12 }, { wch: 12 }, { wch: 18 }];
            wsVal['!merges'] = [
                { s: { r: 0, c: 0 }, e: { r: 0, c: 5 } },
                { s: { r: 8, c: 0 }, e: { r: 8, c: 4 } },
                { s: { r: 10, c: 0 }, e: { r: 10, c: 5 } },
            ];
            XLSX.utils.book_append_sheet(wb, wsVal, 'Valuation Summary');

            // ── Sheet 6: Ratios & Metrics ──
            setExportProgress(68, 'Building Ratios & Metrics...', '');
            const ratiosData = [
                ['Financial Ratios & Metrics -- ' + modelData.company, '', '', '', '', '', ''],
                [''],
                ['Profitability'],
                [''],
                ['Metric', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Trend'],
            ];
            const profMetrics = [
                ['Gross Margin %', ...modelData.rev.map((r, i) => (r - r * 0.55) / r * 100), 'Improving'],
                ['EBITDA Margin %', ...modelData.ebitda.map((e, i) => e / modelData.rev[i] * 100), 'Stable'],
                ['EBIT Margin %', ...modelData.ebit.map((e, i) => e / modelData.rev[i] * 100), 'Stable'],
                ['Net Margin %', ...modelData.ni.map((n, i) => n / modelData.rev[i] * 100), 'Improving'],
                ['ROE %', ...modelData.roe, 'Strong'],
                ['ROA %', ...modelData.ni.map((n, i) => n / (modelData.rev[i] * 1.5) * 100), 'Stable'],
            ];
            profMetrics.forEach(r => ratiosData.push(r.map((v, i) => i > 0 && i < 6 && typeof v === 'number' ? xn(v / 100, '0.0%') : v)));
            ratiosData.push(
                [''],
                ['Leverage & Liquidity'],
                [''],
                ['Metric', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Trend'],
                ['Debt / Equity', ...modelData.rev.map(() => p.netDebt / 100), 'Stable'],
                ['Interest Coverage', ...modelData.ebit.map(e => e / (p.netDebt * 0.08)), 'Strong'],
                ['Current Ratio', ...modelData.rev.map(() => 1.85), 'Stable']
            );
            ratiosData.push(
                [''],
                ['Efficiency'],
                [''],
                ['Metric', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Trend'],
                ['Asset Turnover', ...modelData.rev.map(r => r / (r * 1.5)), 'Stable'],
                ['FCF Conversion %', ...modelData.fcf.map((f, i) => f / modelData.ebitda[i] * 100), 'Strong'],
                ['Revenue per Share (Rs)', ...modelData.rev.map(r => r / p.shares), 'Growing']
            );
            let wsRatios = XLSX.utils.aoa_to_sheet(ratiosData);
            wsRatios['!cols'] = [{ wch: 26 }, { wch: 12 }, { wch: 12 }, { wch: 12 }, { wch: 12 }, { wch: 12 }, { wch: 14 }];
            wsRatios['!merges'] = [
                { s: { r: 0, c: 0 }, e: { r: 0, c: 6 } },
                { s: { r: 2, c: 0 }, e: { r: 2, c: 6 } },
                { s: { r: 10, c: 0 }, e: { r: 10, c: 6 } },
                { s: { r: 17, c: 0 }, e: { r: 17, c: 6 } },
            ];
            XLSX.utils.book_append_sheet(wb, wsRatios, 'Ratios & Metrics');

            // ── Sheet 7: Sensitivity Analysis ──
            setExportProgress(78, 'Building Sensitivity Analysis...', '');
            const sensWacc = [p.wacc - 2, p.wacc - 1, p.wacc, p.wacc + 1, p.wacc + 2];
            const sensTgr = [p.tgr - 1, p.tgr - 0.5, p.tgr, p.tgr + 0.5, p.tgr + 1];
            const sensData = [
                ['Sensitivity Analysis -- ' + modelData.company, '', '', '', '', ''],
                [''],
                ['DCF Fair Value (Rs) -- Sensitivity to WACC & Terminal Growth'],
                [''],
                ['WACC \\ TGR', ...sensTgr.map(t => t.toFixed(1) + '%')],
            ];
            sensWacc.forEach(w => {
                const row = [w.toFixed(1) + '%'];
                sensTgr.forEach(t => {
                    const tv = modelData.fcf[4] * (1 + t / 100) / ((w - t) / 100);
                    const pvTv = tv / Math.pow(1 + w / 100, 5);
                    const ev = modelData.pvFcf + pvTv;
                    const eq = ev - p.netDebt;
                    row.push(xn(eq / p.shares, 'Rs#,##0'));
                });
                sensData.push(row);
            });
            sensData.push(
                [''],
                ['Base Case highlighted. Values decrease as WACC increases or TGR decreases.']
            );
            let wsSens = XLSX.utils.aoa_to_sheet(sensData);
            wsSens['!cols'] = [{ wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 14 }];
            wsSens['!merges'] = [
                { s: { r: 0, c: 0 }, e: { r: 0, c: 5 } },
                { s: { r: 2, c: 0 }, e: { r: 2, c: 5 } },
            ];
            XLSX.utils.book_append_sheet(wb, wsSens, 'Sensitivity');

            // ── Sheet 8: Scenarios ──
            setExportProgress(88, 'Building Scenario Analysis...', '');
            const bullModel = generateModel({ ...p, growth1: p.growth1 * 1.3, ebitdaMargin: p.ebitdaMargin * 1.1, wacc: p.wacc * 0.9 });
            const bearModel = generateModel({ ...p, growth1: p.growth1 * 0.6, ebitdaMargin: p.ebitdaMargin * 0.85, wacc: p.wacc * 1.15 });
            const weightedVal = bullModel.dcfPrice * 0.25 + modelData.dcfPrice * 0.55 + bearModel.dcfPrice * 0.20;
            const scenData = [
                ['Scenario Analysis -- ' + modelData.company, '', '', '', '', '', ''],
                [''],
                ['Scenario', 'Revenue Growth', 'EBITDA Margin', 'WACC', 'Fair Value (Rs)', 'Upside', 'Probability'],
                ['Bull', p.growth1 * 1.3 + '%', (p.ebitdaMargin * 1.1).toFixed(1) + '%', (p.wacc * 0.9).toFixed(1) + '%', xn(bullModel.dcfPrice, 'Rs#,##0'), xn(bullModel.upside / 100, '0.0%'), '25%'],
                ['Base', p.growth1 + '%', p.ebitdaMargin + '%', p.wacc.toFixed(1) + '%', xn(modelData.dcfPrice, 'Rs#,##0'), xn(modelData.upside / 100, '0.0%'), '55%'],
                ['Bear', p.growth1 * 0.6 + '%', (p.ebitdaMargin * 0.85).toFixed(1) + '%', (p.wacc * 1.15).toFixed(1) + '%', xn(bearModel.dcfPrice, 'Rs#,##0'), xn(bearModel.upside / 100, '0.0%'), '20%'],
                [''],
                ['Probability-Weighted Fair Value', '', '', '', xn(weightedVal, 'Rs#,##0'), '', ''],
            ];
            let wsScen = XLSX.utils.aoa_to_sheet(scenData);
            wsScen['!cols'] = [{ wch: 18 }, { wch: 16 }, { wch: 16 }, { wch: 12 }, { wch: 16 }, { wch: 12 }, { wch: 14 }];
            wsScen['!merges'] = [
                { s: { r: 0, c: 0 }, e: { r: 0, c: 6 } },
                { s: { r: 7, c: 0 }, e: { r: 7, c: 3 } },
            ];
            XLSX.utils.book_append_sheet(wb, wsScen, 'Scenarios');

            // ── Write file ──
            setExportProgress(95, 'Finalizing workbook...', 'Saving file');
            XLSX.writeFile(wb, `${safeName}_Equity_Research_${now.toISOString().split('T')[0]}.xlsx`);
            setExportProgress(100, 'Download complete!', '');
            showToast('Professional Excel report downloaded!');
        }

        // ── Draw a simple bar chart with jsPDF primitives ──
        function drawPdfBarChart(doc, x, y, w, h, labels, values, title, colorRgb) {
            doc.setFontSize(8);
            doc.setTextColor(60, 60, 60);
            doc.setFont('helvetica', 'bold');
            doc.text(title, x, y - 4);
            doc.setFont('helvetica', 'normal');

            const maxVal = Math.max(...values) * 1.1;
            const barCount = values.length;
            const barW = (w - (barCount + 1) * 6) / barCount;
            const chartBottom = y + h;

            // Axis lines
            doc.setDrawColor(200, 200, 200);
            doc.setLineWidth(0.3);
            doc.line(x, chartBottom, x + w, chartBottom);
            doc.line(x, y, x, chartBottom);

            // Zero line
            const zeroY = chartBottom - (0 / maxVal) * h;
            doc.setDrawColor(180, 180, 180);
            doc.setLineDashPattern([2, 2], 0);
            doc.line(x, zeroY, x + w, zeroY);
            doc.setLineDashPattern([], 0);

            values.forEach((v, i) => {
                const barX = x + 6 + i * (barW + 6);
                const barH = (Math.abs(v) / maxVal) * h;
                const barY = v >= 0 ? chartBottom - barH : chartBottom;

                // Bar
                doc.setFillColor(...colorRgb);
                doc.rect(barX, barY, barW, barH, 'F');
                doc.setDrawColor(150, 150, 150);
                doc.rect(barX, barY, barW, barH, 'S');

                // Value label
                doc.setFontSize(6);
                doc.setTextColor(40, 40, 40);
                const labelY = v >= 0 ? barY - 2 : barY + barH + 5;
                doc.text('Rs' + v.toFixed(0), barX + barW / 2, labelY, { align: 'center' });

                // X label
                doc.setFontSize(6);
                doc.setTextColor(80, 80, 80);
                doc.text(labels[i], barX + barW / 2, chartBottom + 6, { align: 'center' });
            });
        }

        // ── COMPREHENSIVE PROFESSIONAL PDF EXPORT ──
        async function exportProfessionalPDF() {
            if (!modelData) { showToast('Run analysis first'); return; }
            const { jsPDF } = window.jspdf;
            if (!jsPDF) { showToast('PDF library not loaded. Please refresh.'); return; }

            setExportProgress(3, 'Initializing PDF engine...', 'Preparing 8-page equity research report');
            await new Promise(r => setTimeout(r, 200));

            const p = getCurrentParams();
            const doc = new jsPDF('p', 'mm', 'a4');
            const pageW = 210, pageH = 297;
            const margin = 16;
            const now = new Date();
            const dateStr = now.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
            const safeName = (modelData.company || 'Company').replace(/[^a-zA-Z0-9\s]/g, '');

            // Color palette (RGB arrays)
            const c = {
                primary: [37, 99, 235],
                primaryDark: [29, 78, 216],
                accent: [16, 185, 129],
                warning: [245, 158, 11],
                danger: [239, 68, 68],
                dark: [31, 41, 55],
                medium: [75, 85, 99],
                light: [156, 163, 175],
                bgLight: [249, 250, 251],
                border: [229, 231, 235],
                white: [255, 255, 255]
            };

            // ── Helper: header/footer ──
            function addHeader(pageNum) {
                doc.setFillColor(...c.primary);
                doc.rect(0, 0, pageW, 10, 'F');
                doc.setFontSize(7);
                doc.setTextColor(...c.white);
                doc.setFont('helvetica', 'normal');
                doc.text('dsFinancial - Equity Research', margin, 6.5);
                doc.text('CONFIDENTIAL', pageW - margin - 22, 6.5);
                doc.setDrawColor(...c.border);
                doc.line(margin, 12, pageW - margin, 12);
            }
            function addFooter(pageNum, total) {
                doc.setDrawColor(...c.border);
                doc.line(margin, pageH - 14, pageW - margin, pageH - 14);
                doc.setFontSize(7);
                doc.setTextColor(...c.light);
                doc.text(safeName + ' - DCF Valuation Model - ' + dateStr, margin, pageH - 8);
                doc.text('Page ' + pageNum + ' of ' + total, pageW - margin - 18, pageH - 8);
            }

            // ── PAGE 1: COVER ──
            setExportProgress(10, 'Designing cover page...', '');
            doc.setFillColor(...c.primaryDark);
            doc.rect(0, 0, pageW, 70, 'F');
            doc.setFillColor(...c.primary);
            doc.rect(0, 0, pageW, 60, 'F');
            doc.setFillColor(...c.accent);
            doc.rect(0, 60, pageW, 3, 'F');

            doc.setTextColor(...c.white);
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(11);
            doc.text('EQUITY RESEARCH REPORT', margin, 22);
            doc.setFontSize(26);
            doc.text(safeName, margin, 38);
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            doc.text('5-Year DCF Valuation Model  |  ' + dateStr, margin, 48);

            const ratingColor = modelData.rating === 'BUY' ? c.accent : modelData.rating === 'HOLD' ? c.warning : c.danger;
            doc.setFillColor(...ratingColor);
            doc.roundedRect(pageW - margin - 38, 24, 38, 14, 3, 3, 'F');
            doc.setTextColor(...c.white);
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(12);
            doc.text(modelData.rating, pageW - margin - 19, 33, { align: 'center' });

            // Key metrics cards
            setExportProgress(15, 'Adding key metrics...', '');
            const metrics = [
                { label: 'Current Price', value: 'Rs' + modelData.price.toLocaleString('en-IN') },
                { label: 'Fair Value', value: 'Rs' + modelData.dcfPrice.toFixed(0) },
                { label: 'Target Price', value: 'Rs' + modelData.target.toFixed(0) },
                { label: 'Upside', value: (modelData.upside > 0 ? '+' : '') + modelData.upside.toFixed(1) + '%', color: modelData.upside > 0 ? c.accent : c.danger },
            ];
            const cardW = (pageW - margin * 2 - 9) / 4;
            metrics.forEach((m, i) => {
                const cx = margin + i * (cardW + 3);
                doc.setFillColor(...c.bgLight);
                doc.setDrawColor(...c.border);
                doc.roundedRect(cx, 82, cardW, 28, 2, 2, 'FD');
                doc.setTextColor(...c.medium);
                doc.setFontSize(7);
                doc.setFont('helvetica', 'normal');
                doc.text(m.label, cx + 4, 90);
                doc.setTextColor(...(m.color || c.dark));
                doc.setFontSize(11);
                doc.setFont('helvetica', 'bold');
                doc.text(m.value, cx + 4, 100);
            });

            // Executive summary box
            setExportProgress(20, 'Writing executive summary...', '');
            doc.setFillColor(...c.bgLight);
            doc.setDrawColor(...c.border);
            doc.roundedRect(margin, 118, pageW - margin * 2, 48, 2, 2, 'FD');
            doc.setTextColor(...c.primary);
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            doc.text('EXECUTIVE SUMMARY', margin + 6, 128);
            doc.setTextColor(...c.dark);
            doc.setFontSize(8);
            doc.setFont('helvetica', 'normal');
            const cagr = (modelData.cagr * 100).toFixed(1);
            const summary = [
                `We initiate coverage on ${safeName} with a ${modelData.rating} rating and a fair value of Rs${modelData.dcfPrice.toFixed(0)} per share,`,
                `implying ${modelData.upside > 0 ? 'an upside of' : 'a downside of'} ${Math.abs(modelData.upside).toFixed(1)}% from the current market price of Rs${modelData.price}.`,
                ``,
                `Revenue is projected to grow at a ${cagr}% CAGR over the 5-year forecast period, reaching Rs${modelData.rev[4].toFixed(0)} Cr by Year 5.`,
                `EBITDA margins are expected to remain stable at ~${p.ebitdaMargin}%, generating strong free cash flows of Rs${modelData.fcf[4].toFixed(0)} Cr in Year 5.`,
                `Our DCF-derived enterprise value of Rs${modelData.ev.toFixed(0)} Cr implies an EV/EBITDA multiple of ${(modelData.ev / modelData.ebitda[4]).toFixed(1)}x on Year 5 EBITDA.`
            ];
            let y = 134;
            summary.forEach(line => {
                if (line) {
                    const split = doc.splitTextToSize(line, pageW - margin * 2 - 12);
                    doc.text(split, margin + 6, y);
                    y += split.length * 3.5;
                } else { y += 2; }
            });

            // Assumptions table
            setExportProgress(25, 'Adding assumptions table...', '');
            doc.setTextColor(...c.primary);
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            doc.text('KEY ASSUMPTIONS', margin, 176);

            const assumptions = [
                ['Revenue Growth (Y1-Y2)', p.growth1 + '%', 'Revenue Growth (Y3-Y5)', p.growth2 + '%'],
                ['EBITDA Margin', p.ebitdaMargin + '%', 'Tax Rate', p.taxRate + '%'],
                ['WACC', p.wacc + '%', 'Terminal Growth Rate', p.tgr + '%'],
                ['Net Debt', 'Rs' + p.netDebt + ' Cr', 'Shares Outstanding', p.shares + ' Cr'],
                ['D&A / Revenue', '3.0%', 'CapEx / Revenue', '5.0%'],
            ];
            doc.autoTable({
                startY: 180,
                margin: { left: margin, right: margin },
                body: assumptions,
                theme: 'grid',
                styles: { fontSize: 8, cellPadding: 3, font: 'helvetica', textColor: c.dark },
                headStyles: { fillColor: c.primary, textColor: c.white, fontStyle: 'bold' },
                alternateRowStyles: { fillColor: c.bgLight },
                columnStyles: {
                    0: { fontStyle: 'bold', fillColor: c.bgLight },
                    1: { halign: 'right' },
                    2: { fontStyle: 'bold', fillColor: c.bgLight },
                    3: { halign: 'right' }
                },
                showHead: false,
            });
            addFooter(1, 8);

            // ── PAGE 2: FINANCIAL PROJECTIONS ──
            setExportProgress(35, 'Building financial projections...', '');
            doc.addPage();
            addHeader(2);
            doc.setTextColor(...c.primary);
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text('Financial Projections', margin, 22);
            doc.setTextColor(...c.medium);
            doc.setFontSize(8);
            doc.setFont('helvetica', 'normal');
            doc.text('All figures in Rs Crores unless otherwise stated', margin, 27);

            const projBody = [
                ['Revenue', ...modelData.rev.map(v => v.toFixed(1))],
                ['YoY Growth %', '', ...modelData.rev.slice(1).map((r, i) => ((r / modelData.rev[i] - 1) * 100).toFixed(1) + '%')],
                ['EBITDA', ...modelData.ebitda.map(v => v.toFixed(1))],
                ['EBITDA Margin %', ...modelData.ebitda.map((e, i) => (e / modelData.rev[i] * 100).toFixed(1) + '%')],
                ['EBIT', ...modelData.ebit.map(v => v.toFixed(1))],
                ['EBIT Margin %', ...modelData.ebit.map((e, i) => (e / modelData.rev[i] * 100).toFixed(1) + '%')],
                ['Net Income', ...modelData.ni.map(v => v.toFixed(1))],
                ['Net Margin %', ...modelData.ni.map((n, i) => (n / modelData.rev[i] * 100).toFixed(1) + '%')],
                ['Free Cash Flow', ...modelData.fcf.map(v => v.toFixed(1))],
                ['FCF Margin %', ...modelData.fcf.map((f, i) => (f / modelData.rev[i] * 100).toFixed(1) + '%')],
                ['ROE %', ...modelData.roe.map(v => v.toFixed(1) + '%')],
            ];
            doc.autoTable({
                startY: 32,
                margin: { left: margin, right: margin },
                head: [['Metric', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5']],
                body: projBody,
                theme: 'grid',
                styles: { fontSize: 8, cellPadding: 3, font: 'helvetica', textColor: c.dark },
                headStyles: { fillColor: c.primary, textColor: c.white, fontStyle: 'bold' },
                alternateRowStyles: { fillColor: c.bgLight },
                columnStyles: { 0: { fontStyle: 'bold', fillColor: [243, 244, 246] } },
            });
            addFooter(2, 8);

            // ── PAGE 3: DCF DETAIL ──
            setExportProgress(45, 'Building DCF detail...', '');
            doc.addPage();
            addHeader(3);
            doc.setTextColor(...c.primary);
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text('DCF Valuation Detail', margin, 22);

            const dcfBody = modelData.fcf.map((f, i) => {
                const df = 1 / Math.pow(1 + p.wacc / 100, i + 1);
                return [
                    'Year ' + (i + 1),
                    f.toFixed(1),
                    df.toFixed(4),
                    (f * df).toFixed(1)
                ];
            });
            doc.autoTable({
                startY: 28,
                margin: { left: margin, right: margin },
                head: [['Year', 'Free Cash Flow (Rs Cr)', 'Discount Factor', 'PV of FCF (Rs Cr)']],
                body: dcfBody,
                theme: 'grid',
                styles: { fontSize: 9, cellPadding: 3, font: 'helvetica', textColor: c.dark },
                headStyles: { fillColor: c.primary, textColor: c.white, fontStyle: 'bold' },
                alternateRowStyles: { fillColor: c.bgLight },
            });

            const bridgeY = doc.lastAutoTable.finalY + 10;
            doc.setTextColor(...c.primary);
            doc.setFontSize(11);
            doc.setFont('helvetica', 'bold');
            doc.text('Valuation Bridge', margin, bridgeY);

            const bridgeItems = [
                ['Sum of PV of FCF (Y1-Y5)', modelData.pvFcf.toFixed(1)],
                ['Terminal Value', modelData.tv.toFixed(1)],
                ['PV of Terminal Value', modelData.pvTv.toFixed(1)],
                ['Enterprise Value', modelData.ev.toFixed(1)],
                ['(-) Net Debt', '(' + p.netDebt.toFixed(1) + ')'],
                ['Equity Value', modelData.eq.toFixed(1)],
                ['Shares Outstanding (Cr)', p.shares.toFixed(1)],
                ['Fair Value per Share (Rs)', modelData.dcfPrice.toFixed(2)],
                ['Current Market Price (Rs)', modelData.price.toFixed(2)],
                ['Upside / (Downside)', (modelData.upside > 0 ? '+' : '') + modelData.upside.toFixed(1) + '%'],
            ];
            doc.autoTable({
                startY: bridgeY + 4,
                margin: { left: margin, right: margin },
                body: bridgeItems,
                theme: 'grid',
                styles: { fontSize: 9, cellPadding: 3, font: 'helvetica', textColor: c.dark },
                alternateRowStyles: { fillColor: c.bgLight },
                columnStyles: {
                    0: { fontStyle: 'bold', fillColor: [243, 244, 246] },
                    1: { halign: 'right', fontStyle: 'bold' }
                },
                showHead: false,
                didParseCell: function(data) {
                    if (data.row.index === 3) { data.cell.styles.fillColor = [219, 234, 254]; data.cell.styles.fontStyle = 'bold'; }
                    if (data.row.index === 5) { data.cell.styles.fillColor = [209, 250, 229]; data.cell.styles.fontStyle = 'bold'; }
                    if (data.row.index === 7) { data.cell.styles.fillColor = [254, 243, 199]; data.cell.styles.fontStyle = 'bold'; }
                    if (data.row.index === 9) {
                        data.cell.styles.textColor = modelData.upside > 0 ? c.accent : c.danger;
                        data.cell.styles.fontStyle = 'bold';
                    }
                }
            });
            addFooter(3, 8);

            // ── PAGE 4: VALUATION SUMMARY ──
            setExportProgress(55, 'Building valuation summary...', '');
            doc.addPage();
            addHeader(4);
            doc.setTextColor(...c.primary);
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text('Valuation Summary', margin, 22);

            const peVal = modelData.eq / modelData.ni[4] * 20;
            const evEbitdaVal = modelData.ev / modelData.ebitda[4] * 8;
            const grahamVal = Math.sqrt(22.5 * (modelData.ni[4] / p.shares) * 50);
            const valBody = [
                ['DCF (Primary)', 'Rs' + modelData.dcfPrice.toFixed(0), (modelData.upside > 0 ? '+' : '') + modelData.upside.toFixed(1) + '%', modelData.rating, '40%', 'Rs' + (modelData.dcfPrice * 0.40).toFixed(0)],
                ['P/E Multiple (20x)', 'Rs' + peVal.toFixed(0), ((peVal / modelData.price - 1) * 100).toFixed(1) + '%', peVal > modelData.price * 1.2 ? 'BUY' : 'HOLD', '25%', 'Rs' + (peVal * 0.25).toFixed(0)],
                ['EV/EBITDA (8x)', 'Rs' + evEbitdaVal.toFixed(0), ((evEbitdaVal / modelData.price - 1) * 100).toFixed(1) + '%', 'BUY', '20%', 'Rs' + (evEbitdaVal * 0.20).toFixed(0)],
                ['Graham Formula', 'Rs' + grahamVal.toFixed(0), ((grahamVal / modelData.price - 1) * 100).toFixed(1) + '%', 'HOLD', '15%', 'Rs' + (grahamVal * 0.15).toFixed(0)],
            ];
            doc.autoTable({
                startY: 28,
                margin: { left: margin, right: margin },
                head: [['Method', 'Fair Value', 'Upside', 'Signal', 'Weight', 'Weighted Value']],
                body: valBody,
                theme: 'grid',
                styles: { fontSize: 9, cellPadding: 3, font: 'helvetica', textColor: c.dark },
                headStyles: { fillColor: c.primary, textColor: c.white, fontStyle: 'bold' },
                alternateRowStyles: { fillColor: c.bgLight },
            });

            const blendedY = doc.lastAutoTable.finalY + 8;
            doc.setFillColor(...c.primary);
            doc.roundedRect(margin, blendedY, pageW - margin * 2, 14, 2, 2, 'F');
            doc.setTextColor(...c.white);
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            const blendedVal = modelData.dcfPrice * 0.40 + peVal * 0.25 + evEbitdaVal * 0.20 + grahamVal * 0.15;
            doc.text('Blended Fair Value (Weighted Average): Rs' + blendedVal.toFixed(0), margin + 6, blendedY + 9);

            const kmY = blendedY + 22;
            doc.setTextColor(...c.primary);
            doc.setFontSize(11);
            doc.setFont('helvetica', 'bold');
            doc.text('Key Valuation Metrics', margin, kmY);

            const kmBody = [
                ['Enterprise Value', 'Rs' + modelData.ev.toFixed(0) + ' Cr', 'Equity Value', 'Rs' + modelData.eq.toFixed(0) + ' Cr'],
                ['Implied EV/EBITDA', (modelData.ev / modelData.ebitda[4]).toFixed(1) + 'x', 'Implied P/E', (modelData.eq / modelData.ni[4]).toFixed(1) + 'x'],
                ['Implied P/B', (modelData.eq / (modelData.equity[4] || 100)).toFixed(1) + 'x', 'FCF Yield', (modelData.fcf[4] / modelData.eq * 100).toFixed(1) + '%'],
            ];
            doc.autoTable({
                startY: kmY + 4,
                margin: { left: margin, right: margin },
                body: kmBody,
                theme: 'grid',
                styles: { fontSize: 9, cellPadding: 3, font: 'helvetica', textColor: c.dark },
                alternateRowStyles: { fillColor: c.bgLight },
                columnStyles: { 0: { fontStyle: 'bold', fillColor: [243, 244, 246] }, 2: { fontStyle: 'bold', fillColor: [243, 244, 246] } },
                showHead: false,
            });
            addFooter(4, 8);

            // ── PAGE 5: SENSITIVITY ──
            setExportProgress(65, 'Building sensitivity matrix...', '');
            doc.addPage();
            addHeader(5);
            doc.setTextColor(...c.primary);
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text('Sensitivity Analysis', margin, 22);
            doc.setTextColor(...c.medium);
            doc.setFontSize(8);
            doc.setFont('helvetica', 'normal');
            doc.text('DCF Fair Value (Rs) -- Sensitivity to WACC & Terminal Growth Rate', margin, 27);

            const sensWacc = [p.wacc - 2, p.wacc - 1, p.wacc, p.wacc + 1, p.wacc + 2];
            const sensTgr = [p.tgr - 1, p.tgr - 0.5, p.tgr, p.tgr + 0.5, p.tgr + 1];
            const sensHead = ['WACC \\ TGR', ...sensTgr.map(t => t.toFixed(1) + '%')];
            const sensBody = sensWacc.map(w => {
                const row = [w.toFixed(1) + '%'];
                sensTgr.forEach(t => {
                    const tv = modelData.fcf[4] * (1 + t / 100) / ((w - t) / 100);
                    const pvTv = tv / Math.pow(1 + w / 100, 5);
                    const ev = modelData.pvFcf + pvTv;
                    const eq = ev - p.netDebt;
                    row.push('Rs' + (eq / p.shares).toFixed(0));
                });
                return row;
            });
            doc.autoTable({
                startY: 32,
                margin: { left: margin, right: margin },
                head: [sensHead],
                body: sensBody,
                theme: 'grid',
                styles: { fontSize: 8, cellPadding: 3, font: 'helvetica', textColor: c.dark },
                headStyles: { fillColor: c.primary, textColor: c.white, fontStyle: 'bold' },
                alternateRowStyles: { fillColor: c.bgLight },
                columnStyles: { 0: { fontStyle: 'bold', fillColor: [243, 244, 246] } },
                didParseCell: function(data) {
                    if (data.row.index === 2 && data.column.index === 3) {
                        data.cell.styles.fillColor = [209, 250, 229];
                        data.cell.styles.fontStyle = 'bold';
                    }
                }
            });
            addFooter(5, 8);

            // ── PAGE 6: CHARTS (drawn natively, no canvas capture) ──
            setExportProgress(75, 'Drawing charts...', '');
            doc.addPage();
            addHeader(6);
            doc.setTextColor(...c.primary);
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text('Charts & Visualizations', margin, 22);

            // Revenue bar chart (native jsPDF drawing)
            drawPdfBarChart(doc, margin, 32, (pageW - margin * 2) / 2 - 6, 55, years, modelData.rev, 'Revenue (Rs Cr)', c.primary);
            // FCF bar chart
            drawPdfBarChart(doc, margin + (pageW - margin * 2) / 2 + 6, 32, (pageW - margin * 2) / 2 - 6, 55, years, modelData.fcf, 'Free Cash Flow (Rs Cr)', c.accent);

            // Waterfall description
            const wfY = 105;
            doc.setTextColor(...c.primary);
            doc.setFontSize(11);
            doc.setFont('helvetica', 'bold');
            doc.text('Valuation Waterfall', margin, wfY);
            doc.setTextColor(...c.dark);
            doc.setFontSize(8);
            doc.setFont('helvetica', 'normal');
            const wfText = [
                'The valuation waterfall illustrates the step-by-step bridge from Enterprise Value to Equity Value per share.',
                `Starting with an Enterprise Value of Rs${modelData.ev.toFixed(0)} Cr, we deduct net debt of Rs${p.netDebt} Cr`,
                `to arrive at an Equity Value of Rs${modelData.eq.toFixed(0)} Cr. Dividing by ${p.shares} Cr shares`,
                `yields a fair value of Rs${modelData.dcfPrice.toFixed(0)} per share.`,
                '',
                `The DCF is primarily driven by projected FCFs totaling Rs${modelData.pvFcf.toFixed(0)} Cr in present value,`,
                `plus a terminal value contribution of Rs${modelData.pvTv.toFixed(0)} Cr (present value).`
            ];
            let wfLineY = wfY + 6;
            wfText.forEach(line => {
                if (line) {
                    const split = doc.splitTextToSize(line, pageW - margin * 2);
                    doc.text(split, margin, wfLineY);
                    wfLineY += split.length * 3.5;
                } else { wfLineY += 2; }
            });
            addFooter(6, 8);

            // ── PAGE 7: RATIOS ──
            setExportProgress(85, 'Building ratios page...', '');
            doc.addPage();
            addHeader(7);
            doc.setTextColor(...c.primary);
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text('Financial Ratios & Metrics', margin, 22);

            const ratioBody = [
                ['Gross Margin', ...modelData.rev.map((r, i) => ((r - r * 0.55) / r * 100).toFixed(1) + '%')],
                ['EBITDA Margin', ...modelData.ebitda.map((e, i) => (e / modelData.rev[i] * 100).toFixed(1) + '%')],
                ['EBIT Margin', ...modelData.ebit.map((e, i) => (e / modelData.rev[i] * 100).toFixed(1) + '%')],
                ['Net Margin', ...modelData.ni.map((n, i) => (n / modelData.rev[i] * 100).toFixed(1) + '%')],
                ['FCF Margin', ...modelData.fcf.map((f, i) => (f / modelData.rev[i] * 100).toFixed(1) + '%')],
                ['ROE', ...modelData.roe.map(v => v.toFixed(1) + '%')],
                ['ROA', ...modelData.ni.map((n, i) => (n / (modelData.rev[i] * 1.5) * 100).toFixed(1) + '%')],
                ['Interest Coverage', ...modelData.ebit.map(e => (e / (p.netDebt * 0.08)).toFixed(1) + 'x')],
            ];
            doc.autoTable({
                startY: 28,
                margin: { left: margin, right: margin },
                head: [['Ratio', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5']],
                body: ratioBody,
                theme: 'grid',
                styles: { fontSize: 9, cellPadding: 3, font: 'helvetica', textColor: c.dark },
                headStyles: { fillColor: c.primary, textColor: c.white, fontStyle: 'bold' },
                alternateRowStyles: { fillColor: c.bgLight },
                columnStyles: { 0: { fontStyle: 'bold', fillColor: [243, 244, 246] } },
            });
            addFooter(7, 8);

            // ── PAGE 8: DISCLAIMER ──
            setExportProgress(92, 'Adding disclaimer...', '');
            doc.addPage();
            addHeader(8);
            doc.setTextColor(...c.primary);
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.text('Disclaimer & Methodology', margin, 22);

            doc.setTextColor(...c.dark);
            doc.setFontSize(9);
            doc.setFont('helvetica', 'normal');
            const disclaimers = [
                '1. Investment Risk Warning',
                'Investments in securities are subject to market risks. Past performance is not indicative of future results.',
                'The value of investments may go up or down depending on market conditions and other factors.',
                '',
                '2. Data Sources',
                'This model uses user-provided inputs and simulated data for demonstration purposes. For actual investment',
                'decisions, verified financial statements from company filings (Annual Reports, quarterly results) should be used.',
                '',
                '3. Model Assumptions',
                'The DCF model assumes a going concern, stable tax regime, and consistent capital structure. Changes in',
                'macroeconomic conditions, regulatory environment, or competitive dynamics may materially impact actual outcomes.',
                '',
                '4. Independence',
                'This report is generated algorithmically by the dsFinancial Modelling Engine. It does not represent the views',
                'of any regulated research entity or investment advisor. Users should consult with qualified financial advisors',
                'before making investment decisions.',
                '',
                '5. Methodology',
                'Enterprise Value = Sum of PV of FCF (5-year explicit) + PV of Terminal Value',
                'Terminal Value = FCF(Y5) x (1 + TGR) / (WACC - TGR)',
                'Equity Value = Enterprise Value - Net Debt',
                'Fair Value per Share = Equity Value / Shares Outstanding',
                '',
                'Generated by dsFinancial Modelling Engine on ' + dateStr,
            ];
            let dY = 30;
            disclaimers.forEach((line, i) => {
                if (line) {
                    const isHeader = /^\d\./.test(line);
                    doc.setFont('helvetica', isHeader ? 'bold' : 'normal');
                    doc.setTextColor(...(isHeader ? c.primary : c.dark));
                    const split = doc.splitTextToSize(line, pageW - margin * 2);
                    doc.text(split, margin, dY);
                    dY += split.length * 4.5;
                } else { dY += 2; }
            });
            addFooter(8, 8);

            // Save
            setExportProgress(98, 'Saving PDF...', '');
            doc.save(`${safeName}_Equity_Research_${now.toISOString().split('T')[0]}.pdf`);
            setExportProgress(100, 'Download complete!', '');
            showToast('Professional PDF report downloaded!');
        }
